### ISSUE TITLE
Does not work on JSON code editor

### ISSUE THREAD

**Issue by nanangp** [nanangp/vs-shell-contextmenu#2]
Need to figure out the JSON editor popup menu GUID+ID.
See [here](https://docs.microsoft.com/en-us/archive/blogs/dr._ex/using-enablevsiplogging-to-identify-menus-and-commands-with-vs-2005-sp1) for a way to enable logging of menu IDs.

**Comment by blackboxlogic** [comment]
From the [codeMaid plugin](https://github.com/codecadwallader/codemaid/blob/dev/CodeMaid/CodeMaid.vsct), maybe:
`IDVisualStudioJSONDocumentContextMenu` and `{f718ca06-cf4f-4a0c-9106-e79e9ee5e7cd}`

**Comment by nanangp** [comment]
Cheers for that. Confirmed it with VSIP logging as well. Will do another release as soon as I can figure out #5

**Comment by blackboxlogic** [comment]
Regarding a release, I might have a pull request headed your way in the next day or two for an unrelated bug.

**Comment by blackboxlogic** [comment]
Oh... Just looked at the ticket you were referencing. I've got that fixed! I'll make a PR... maybe tomorrow.
