### ISSUE TITLE
Doesn't work on Solution Items that don't live at the solution root

### ISSUE THREAD

**Issue by nanangp** [nanangp/vs-shell-contextmenu#5]
There's an assumption in the code that a solution item is located at the root (they usually do). But you can actually add items from any location (right click "Solution Items" > Add > Existing item...).

Problem is, the returned ProjectItem from the context menu does not seem to contain its actual location (hence the original assumption). Will have to find a way to dig up the path somehow.

**Comment by blackboxlogic** [comment]
I'm going to skip a long, embarrassing story of how I've ended up in your repo, but the story ends with `projectItem = _dte.Solution.FindProjectItem(projectItem.Name)` then continue normally to get the full path. I haven't actually _looked_ at your code, but I plan to make a PR in the next few days to fix this and another bug (if you haven't already gotten to it).

**Comment by nanangp** [comment]
Just saw that in blackboxlogic/ShellContextMenuExtension@0eb095bb. I'm afraid it doesn't seem to work on my copy of VS2019 (v16.9.0p4) 😕
If you get it working, would you mind reporting back on what version it was tested on?

Kinda surprised that there are people still actually using, much less fixing, something that I forgot about until last year!

**Comment by blackboxlogic** [comment]
This extension is a _must_ if you use tortoise git. Thanks for making it. I hadn't seen what VS extension code looked like until I tried to fix this (and managed fixed it in the wrong fork by mistake). Did you know your extension has a [doppelganger](https://marketplace.visualstudio.com/items?itemName=id1508.ShellContextMenu)?
Looks like you're running a VS preview build? What's the advantage?

**Comment by nanangp** [comment]
> Looks like you're running a VS preview build? What's the advantage?

Was adopting .NET5 quite early on - supported only on VS preview. Been updating along from there (on preview, when stable is released you get updated to the *next* preview). Now targeting .NET6 for a new project (and may settle there, as 6 would be an LTS).

> hadn't seen what VS extension code looked like

They've kinda cleaned up the format a couple years back, so this version would look slightly different to the older fork. Also, much cleaner references (a single Nuget reference to `VSSDK.Shell.*` instead of the mess that it was).

Still atrociously documented. As witnessed here!

**Comment by blackboxlogic** [comment]
I'm checking in to see if you've had time to review the PR, and looking forward to having these features.

**Comment by blackboxlogic** [comment]
P.S. I've been using the unreleased version for a few months and the new features have performed as expected with no issues. I'm looking forward to a 2.1 release so my coworkers to upgrade.

**Comment by nanangp** [comment]
Apologies. Covid had wreaked havoc on a lot of things meant to be done ages ago. 
2.1 is back on the menu now!
