### ISSUE TITLE
Update "Works with" to include VS-2019

### ISSUE THREAD

**Issue by blackboxlogic** [nanangp/vs-shell-contextmenu#8]
The [listing](https://marketplace.visualstudio.com/items?itemName=NanangP.ShellContextMenu&ssr=false#overview) on the marketplace says "**Works with**: Visual Studio 2012, 2013, 2015, 2017", which seems to be **missing 2019**.

Suggest updating that.

**Comment by nanangp** [comment]
That's bizarre. Those fields on the publishing interface are read-only (as it picks them up from the manifest), and currently looks like so:

> <img width="270" src="https://user-images.githubusercontent.com/4198609/110420531-88777000-80ef-11eb-8cd5-e717d7b05ea1.png">

The manifest has the following, which should translate to anything from 11.0 inclusive, up to 17.0 exclusive.
```
<InstallationTarget Id="Microsoft.VisualStudio.IntegratedShell" Version="[11.0, 17.0)" />
...
<Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[11.0,17.0)" DisplayName="Visual Studio core editor" />
```

Will investigate what is actually expected by the Marketplace.

**Comment by nanangp** [comment]
I love bugs that fixes itself unintentionally. 940cd89
