### ISSUE TITLE
VS2022 Support

### ISSUE THREAD

**Issue by nanangp** [nanangp/vs-shell-contextmenu#9]
Gonna be interesting with all the major incoming [changes ](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022).

Also note the [breaking API changes](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/breaking-api-list?view=vs-2022).

**Comment by blackboxlogic** [comment]
Would you like help with this?

**Comment by nanangp** [comment]
Thanks, I've got a build running locally. A couple editors have different guids, but otherwise seems to be stable.

Could use a hand to come up with a single vsix that would work in, say, 2015-2022 without having to publish two separate extensions in the marketplace.  Managed to get one to build & install, but the pre-2022 instances got into dll dependency hell when invoked. Didn't try very hard, so maybe I just missed something obvious.

**Comment by blackboxlogic** [comment]
Regarding "a single vsix", this conversation might help: https://github.com/mayerwin/vs-customize-window-title/issues/64
Also related:
* https://github.com/ow--/vs-subword-navigation/issues/14
* https://github.com/microsoft/VS-PPT/issues/247

**Comment by nanangp** [comment]
Release 2.2 up on marketplace.

@blackboxlogic Cheers for the hints. Got it working by referencing Microsoft.VisualStudio.Sdk v15 and the dependencies that it brings (mentioned in one of them). 

This also means saying goodbye to VS2015 (v14) and earlier. Oh well..  Anyone on VS2012-2015 - I love you, but maybe it's time to upgrade?
